# Generated by Django 2.2.4 on 2019-08-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudWatch_site', '0002_auto_20190825_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
