# Generated by Django 2.2.4 on 2019-08-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudWatch_site', '0003_auto_20190827_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
