# Generated by Django 2.2.4 on 2019-08-29 03:33

from django.db import migrations, models
import django.utils.timezone
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CloudWatch_site', '0004_notification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
