# Generated by Django 2.2.4 on 2019-08-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudWatch_site', '0005_auto_20190828_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
